export const SAMPLEAPI_POST_LOGIN_CREATE = "SAMPLEAPI_POST_LOGIN_CREATE"
export const SAMPLEAPI_POST_LOGIN_CREATE_SUCCEEDED =
  "SAMPLEAPI_POST_LOGIN_CREATE_SUCCEEDED"
export const SAMPLEAPI_POST_LOGIN_CREATE_FAILED =
  "SAMPLEAPI_POST_LOGIN_CREATE_FAILED"
